project_id = "wlvuswftjdpnqlyrzquz"

[functions.parse-invoice]
verify_jwt = true

[functions.get-invoice]
verify_jwt = true

[functions.create-deal]
verify_jwt = true

[functions.tx-webhook]
verify_jwt = false
