[project]
name = "smart-invoice-dao"
description = "AI-powered Bitcoin-native DAO invoicing via Clarity escrow on Stacks"
authors = ["bitmind"]
telemetry = false
requirements = []

[contracts.escrow]
path = "contracts/escrow.clar"
clarity_version = 2

[contracts.escrow-secure]
path = "contracts/escrow-secure.clar"
clarity_version = 2

[contracts.escrow-governance]
path = "contracts/escrow-governance.clar"
clarity_version = 2

[contracts.governance-multisig]
path = "contracts/governance-multisig.clar"
clarity_version = 2

[contracts.mock-token]
path = "contracts/mock-token.clar"
clarity_version = 2

[repl]
costs_version = 2
clarity_version = 2

[repl.analysis]
passes = ["check_checker"]

