// Mock invoice data
export const mockInvoices = [
    {
        id: 'INV-001',
        projectTitle: 'DeFi Protocol Smart Contract Development',
        description: 'Build a comprehensive DeFi protocol with lending, borrowing, and staking features. Includes security audit and deployment.',
        clientAddress: 'SP2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKNRV9EJ7',
        contractorAddress: 'SP3FGQ8Z7JY4C9P7NDJMM5X1EQK3RKY4S8MP9QX2V',
        arbitratorAddress: 'SP1KFJXJ8Q9HV7YP3WGH98JN3JKZM7RQ2TKXHXF4N',
        totalAmount: 8000,
        currency: 'sBTC',
        status: 'ACTIVE',
        contractAddress: '0x1234...5678',
        milestones: [
            {
                id: 'MS-001-1',
                invoiceId: 'INV-001',
                amount: 2400,
                description: 'Smart contract architecture and initial development',
                condition: 'Code review approval and testnet deployment',
                status: 'RELEASED',
                sequence: 1,
                completedAt: '2024-11-15T10:00:00Z',
            },
            {
                id: 'MS-001-2',
                invoiceId: 'INV-001',
                amount: 4000,
                description: 'Full implementation and security audit',
                condition: 'Security audit report with no critical issues',
                status: 'APPROVED',
                sequence: 2,
            },
            {
                id: 'MS-001-3',
                invoiceId: 'INV-001',
                amount: 1600,
                description: 'Mainnet deployment and documentation',
                condition: 'Successful mainnet deployment and complete docs',
                status: 'PENDING',
                sequence: 3,
            },
        ],
        createdAt: '2024-10-01T09:00:00Z',
        updatedAt: '2024-11-15T10:00:00Z',
        daoName: 'DeFi DAO',
        projectType: 'Smart Contract Development',
        timeline: '8 weeks',
    },
    {
        id: 'INV-002',
        projectTitle: 'DAO Website Redesign',
        description: 'Complete redesign of DAO website with modern UI/UX, responsive design, and integration with Stacks wallet.',
        clientAddress: 'SP2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKNRV9EJ7',
        contractorAddress: 'SP1ABCD8Z7JY4C9P7NDJMM5X1EQK3RKY4S8MPXYZ1',
        arbitratorAddress: 'SP1KFJXJ8Q9HV7YP3WGH98JN3JKZM7RQ2TKXHXF4N',
        totalAmount: 4500,
        currency: 'sBTC',
        status: 'ACTIVE',
        milestones: [
            {
                id: 'MS-002-1',
                invoiceId: 'INV-002',
                amount: 1350,
                description: 'UI/UX design mockups',
                condition: 'Design approval from DAO governance',
                status: 'RELEASED',
                sequence: 1,
                completedAt: '2024-11-10T14:00:00Z',
            },
            {
                id: 'MS-002-2',
                invoiceId: 'INV-002',
                amount: 2250,
                description: 'Frontend development and wallet integration',
                condition: 'Working prototype with wallet connection',
                status: 'PENDING',
                sequence: 2,
            },
            {
                id: 'MS-002-3',
                invoiceId: 'INV-002',
                amount: 900,
                description: 'Final deployment and testing',
                condition: 'Live website with all features working',
                status: 'PENDING',
                sequence: 3,
            },
        ],
        createdAt: '2024-10-15T11:00:00Z',
        updatedAt: '2024-11-10T14:00:00Z',
        daoName: 'NFT Collective',
        projectType: 'Frontend Development',
        timeline: '6 weeks',
    },
    {
        id: 'INV-003',
        projectTitle: 'Marketing Campaign Management',
        description: 'Comprehensive marketing campaign including content creation, social media management, and community growth for Q1 2025.',
        clientAddress: 'SP3WEB3GUILD9MP66SW86PYKKNRV9EJ7MP66SW86P',
        contractorAddress: 'SP2MARKET1234C9P7NDJMM5X1EQK3RKY4S8MPXYZ',
        arbitratorAddress: 'SP1KFJXJ8Q9HV7YP3WGH98JN3JKZM7RQ2TKXHXF4N',
        totalAmount: 5000,
        currency: 'sBTC',
        status: 'COMPLETED',
        milestones: [
            {
                id: 'MS-003-1',
                invoiceId: 'INV-003',
                amount: 1500,
                description: 'Campaign strategy and content calendar',
                condition: 'Approved marketing strategy document',
                status: 'RELEASED',
                sequence: 1,
                completedAt: '2024-10-05T09:00:00Z',
            },
            {
                id: 'MS-003-2',
                invoiceId: 'INV-003',
                amount: 2500,
                description: 'Content creation and social media execution',
                condition: '50+ posts published with engagement metrics',
                status: 'RELEASED',
                sequence: 2,
                completedAt: '2024-11-01T16:00:00Z',
            },
            {
                id: 'MS-003-3',
                invoiceId: 'INV-003',
                amount: 1000,
                description: 'Campaign report and analytics',
                condition: 'Final report with ROI analysis',
                status: 'RELEASED',
                sequence: 3,
                completedAt: '2024-11-20T10:00:00Z',
            },
        ],
        createdAt: '2024-09-15T10:00:00Z',
        updatedAt: '2024-11-20T10:00:00Z',
        daoName: 'Web3 Guild',
        projectType: 'Marketing',
        timeline: '10 weeks',
    },
    {
        id: 'INV-004',
        projectTitle: 'Smart Contract Security Audit',
        description: 'Comprehensive security audit of Clarity smart contracts for DEX protocol, including automated testing and manual review.',
        clientAddress: 'SP2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKNRV9EJ7',
        contractorAddress: 'SP4SECURITY1Z7JY4C9P7NDJMM5X1EQK3RKY4S8M',
        arbitratorAddress: 'SP1KFJXJ8Q9HV7YP3WGH98JN3JKZM7RQ2TKXHXF4N',
        totalAmount: 3500,
        currency: 'sBTC',
        status: 'ACTIVE',
        milestones: [
            {
                id: 'MS-004-1',
                invoiceId: 'INV-004',
                amount: 1050,
                description: 'Preliminary audit and automated testing',
                condition: 'Initial audit report with findings',
                status: 'RELEASED',
                sequence: 1,
                completedAt: '2024-11-18T15:00:00Z',
            },
            {
                id: 'MS-004-2',
                invoiceId: 'INV-004',
                amount: 2450,
                description: 'Comprehensive manual review and final report',
                condition: 'Final security audit report with recommendations',
                status: 'PENDING',
                sequence: 2,
            },
        ],
        createdAt: '2024-11-01T08:00:00Z',
        updatedAt: '2024-11-18T15:00:00Z',
        daoName: 'DeFi DAO',
        projectType: 'Security Audit',
        timeline: '3 weeks',
    },
    {
        id: 'INV-005',
        projectTitle: 'NFT Marketplace Backend Development',
        description: 'Build robust backend infrastructure for NFT marketplace including APIs, database design, and integration with IPFS.',
        clientAddress: 'SP3WEB3GUILD9MP66SW86PYKKNRV9EJ7MP66SW86P',
        contractorAddress: 'SP5BACKEND123Y4C9P7NDJMM5X1EQK3RKY4S8MPX',
        arbitratorAddress: 'SP1KFJXJ8Q9HV7YP3WGH98JN3JKZM7RQ2TKXHXF4N',
        totalAmount: 6000,
        currency: 'sBTC',
        status: 'DISPUTED',
        milestones: [
            {
                id: 'MS-005-1',
                invoiceId: 'INV-005',
                amount: 1800,
                description: 'Database schema and API design',
                condition: 'Approved architecture document',
                status: 'RELEASED',
                sequence: 1,
                completedAt: '2024-10-20T11:00:00Z',
            },
            {
                id: 'MS-005-2',
                invoiceId: 'INV-005',
                amount: 3000,
                description: 'Core API development and IPFS integration',
                condition: 'Working APIs with test coverage',
                status: 'DISPUTED',
                sequence: 2,
            },
            {
                id: 'MS-005-3',
                invoiceId: 'INV-005',
                amount: 1200,
                description: 'Performance optimization and deployment',
                condition: 'Production-ready deployment',
                status: 'PENDING',
                sequence: 3,
            },
        ],
        createdAt: '2024-10-05T13:00:00Z',
        updatedAt: '2024-11-22T09:00:00Z',
        daoName: 'NFT Collective',
        projectType: 'Backend Development',
        timeline: '7 weeks',
    },
];
// Mock AI parsing function
export const mockAIParseInvoice = async (description) => {
    // Simulate AI processing delay
    await new Promise(resolve => setTimeout(resolve, 1500));
    // Extract numbers for amount estimation
    const amountMatch = description.match(/(\d+(?:,\d+)?(?:\.\d+)?)\s*(sBTC|STX|BTC)/i);
    const totalAmount = amountMatch ? parseFloat(amountMatch[1].replace(',', '')) : 5000;
    // Parse milestones from description
    const milestoneKeywords = ['milestone', 'phase', 'payment', 'stage', 'deliverable'];
    const hasMilestones = milestoneKeywords.some(keyword => description.toLowerCase().includes(keyword));
    const milestones = hasMilestones ? [
        {
            amount: totalAmount * 0.3,
            percentage: 30,
            description: 'Initial development and setup',
            condition: 'Project kickoff and initial deliverables',
            sequence: 1,
        },
        {
            amount: totalAmount * 0.5,
            percentage: 50,
            description: 'Core implementation and testing',
            condition: 'Functional prototype with key features',
            sequence: 2,
        },
        {
            amount: totalAmount * 0.2,
            percentage: 20,
            description: 'Final delivery and documentation',
            condition: 'Complete project with documentation',
            sequence: 3,
        },
    ] : [
        {
            amount: totalAmount * 0.5,
            percentage: 50,
            description: 'Project development',
            condition: 'Milestone completion approval',
            sequence: 1,
        },
        {
            amount: totalAmount * 0.5,
            percentage: 50,
            description: 'Final delivery',
            condition: 'Project completion and approval',
            sequence: 2,
        },
    ];
    return {
        total_amount: totalAmount,
        currency: amountMatch?.[2] || 'sBTC',
        parties: {
            client: 'SP2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKNRV9EJ7',
            contractor: 'SP3FGQ8Z7JY4C9P7NDJMM5X1EQK3RKY4S8MP9QX2V',
        },
        milestones,
        arbitrator: 'SP1KFJXJ8Q9HV7YP3WGH98JN3JKZM7RQ2TKXHXF4N',
        project_scope: description.slice(0, 200),
        project_title: description.slice(0, 60).trim() + '...',
        timeline: '6-8 weeks',
        confidence: 0.94,
    };
};
// Mock DAO data
export const mockDAOs = [
    {
        id: 'DAO-001',
        name: 'DeFi DAO',
        treasuryAddress: 'SP2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKNRV9EJ7',
        totalBudget: 50000,
        availableBudget: 32000,
        activeInvoices: 3,
        completedInvoices: 12,
        members: 156,
        focus: ['DeFi', 'Smart Contracts', 'Security'],
        createdAt: '2024-01-15T00:00:00Z',
    },
    {
        id: 'DAO-002',
        name: 'NFT Collective',
        treasuryAddress: 'SP3NFT8GV1EZ5V2V5RB9MP66SW86PYKKNRV9EJ7',
        totalBudget: 35000,
        availableBudget: 22000,
        activeInvoices: 2,
        completedInvoices: 8,
        members: 89,
        focus: ['NFTs', 'Art', 'Community'],
        createdAt: '2024-03-10T00:00:00Z',
    },
    {
        id: 'DAO-003',
        name: 'Web3 Guild',
        treasuryAddress: 'SP3WEB3GUILD9MP66SW86PYKKNRV9EJ7MP66SW86P',
        totalBudget: 42000,
        availableBudget: 18000,
        activeInvoices: 4,
        completedInvoices: 15,
        members: 234,
        focus: ['Development', 'Education', 'Open Source'],
        createdAt: '2024-02-01T00:00:00Z',
    },
];
// Mock contractor data
export const mockContractors = [
    {
        id: 'CON-001',
        walletAddress: 'SP3FGQ8Z7JY4C9P7NDJMM5X1EQK3RKY4S8MP9QX2V',
        name: 'Alice Johnson',
        rating: 4.9,
        completedProjects: 24,
        totalEarned: 125000,
        skills: ['Clarity', 'Smart Contracts', 'Solidity', 'Security'],
        bio: 'Senior blockchain developer specializing in smart contract development and security audits.',
        availability: 'available',
    },
    {
        id: 'CON-002',
        walletAddress: 'SP1ABCD8Z7JY4C9P7NDJMM5X1EQK3RKY4S8MPXYZ1',
        name: 'Bob Smith',
        rating: 4.8,
        completedProjects: 18,
        totalEarned: 89000,
        skills: ['React', 'TypeScript', 'UI/UX', 'Tailwind CSS'],
        bio: 'Full-stack developer with expertise in modern web technologies and blockchain integrations.',
        availability: 'busy',
    },
    {
        id: 'CON-003',
        walletAddress: 'SP2MARKET1234C9P7NDJMM5X1EQK3RKY4S8MPXYZ',
        name: 'Carol White',
        rating: 4.7,
        completedProjects: 32,
        totalEarned: 145000,
        skills: ['Marketing', 'Content Strategy', 'Community Management', 'Analytics'],
        bio: 'Digital marketing specialist focused on Web3 and DAO community growth.',
        availability: 'available',
    },
];

// Mock platform metrics
export const platformMetrics = {
    totalInvoices: 156,
    totalVolume: 287500,
    successRate: 94.5,
    activeDAOs: 62,
    growthRate: 28.3,
    disputeRate: 3.2,
    averageCompletionTime: 21,
};
