// Mock Data Service - Comprehensive demo data for Stacks Vibe Coding Hackathon
import { InvoiceData, AIParsedInvoice, DAOProfile, ContractorProfile, PlatformStats } from '../types';

// Platform Metrics
export const platformMetrics: PlatformStats = {
  totalInvoices: 1456,
  totalVolume: 3247.8,
  activeDAOs: 62,
  successRate: 96.7,
  averageCompletionTime: 18.5,
  disputeRate: 2.4,
  growthRate: 169.6, // From 23 to 62 DAOs (169.6% growth)
};

// Mock invoice data
export const mockInvoices: InvoiceData[] = [
  {
    id: 'INV-001',
    projectTitle: 'DeFi Protocol Smart Contract Development',
    description: 'Build a comprehensive DeFi protocol with lending, borrowing, and staking features. Includes security audit and deployment.',
    clientAddress: 'SP2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKNRV9EJ7',
    contractorAddress: 'SP3FGQ8Z7JY4C9P7NDJMM5X1EQK3RKY4S8MP9QX2V',
    arbitratorAddress: 'SP1KFJXJ8Q9HV7YP3WGH98JN3JKZM7RQ2TKXHXF4N',
    totalAmount: 8000,
    currency: 'sBTC',
    status: 'ACTIVE',
    contractAddress: '0x1234...5678',
    milestones: [
      {
        id: 'MS-001-1',
        invoiceId: 'INV-001',
        amount: 2400,
        description: 'Smart contract architecture and initial development',
        condition: 'Code review approval and testnet deployment',
        status: 'RELEASED',
        sequence: 1,
        completedAt: '2024-11-15T10:00:00Z',
      },
      {
        id: 'MS-001-2',
        invoiceId: 'INV-001',
        amount: 4000,
        description: 'Full implementation and security audit',
        condition: 'Security audit report with no critical issues',
        status: 'APPROVED',
        sequence: 2,
      },
      {
        id: 'MS-001-3',
        invoiceId: 'INV-001',
        amount: 1600,
        description: 'Mainnet deployment and documentation',
        condition: 'Successful mainnet deployment and complete docs',
        status: 'PENDING',
        sequence: 3,
      },
    ],
    createdAt: '2024-10-01T09:00:00Z',
    updatedAt: '2024-11-15T10:00:00Z',
    daoName: 'DeFi DAO',
    projectType: 'Smart Contract Development',
    timeline: '8 weeks',
  },
  {
    id: 'INV-002',
    projectTitle: 'DAO Website Redesign',
    description: 'Complete redesign of DAO website with modern UI/UX, responsive design, and integration with Stacks wallet.',
    clientAddress: 'SP2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKNRV9EJ7',
    contractorAddress: 'SP1ABCD8Z7JY4C9P7NDJMM5X1EQK3RKY4S8MPXYZ1',
    arbitratorAddress: 'SP1KFJXJ8Q9HV7YP3WGH98JN3JKZM7RQ2TKXHXF4N',
    totalAmount: 4500,
    currency: 'sBTC',
    status: 'ACTIVE',
    milestones: [
      {
        id: 'MS-002-1',
        invoiceId: 'INV-002',
        amount: 1350,
        description: 'UI/UX design mockups',
        condition: 'Design approval from DAO governance',
        status: 'RELEASED',
        sequence: 1,
        completedAt: '2024-11-10T14:00:00Z',
      },
      {
        id: 'MS-002-2',
        invoiceId: 'INV-002',
        amount: 2250,
        description: 'Frontend development and wallet integration',
        condition: 'Working prototype with wallet connection',
        status: 'PENDING',
        sequence: 2,
      },
      {
        id: 'MS-002-3',
        invoiceId: 'INV-002',
        amount: 900,
        description: 'Final deployment and testing',
        condition: 'Live website with all features working',
        status: 'PENDING',
        sequence: 3,
      },
    ],
    createdAt: '2024-10-15T11:00:00Z',
    updatedAt: '2024-11-10T14:00:00Z',
    daoName: 'NFT Collective',
    projectType: 'Frontend Development',
    timeline: '6 weeks',
  },
  {
    id: 'INV-003',
    projectTitle: 'Marketing Campaign Management',
    description: 'Comprehensive marketing campaign including content creation, social media management, and community growth for Q1 2025.',
    clientAddress: 'SP3WEB3GUILD9MP66SW86PYKKNRV9EJ7MP66SW86P',
    contractorAddress: 'SP2MARKET1234C9P7NDJMM5X1EQK3RKY4S8MPXYZ',
    arbitratorAddress: 'SP1KFJXJ8Q9HV7YP3WGH98JN3JKZM7RQ2TKXHXF4N',
    totalAmount: 5000,
    currency: 'sBTC',
    status: 'COMPLETED',
    milestones: [
      {
        id: 'MS-003-1',
        invoiceId: 'INV-003',
        amount: 1500,
        description: 'Campaign strategy and content calendar',
        condition: 'Approved marketing strategy document',
        status: 'RELEASED',
        sequence: 1,
        completedAt: '2024-10-05T09:00:00Z',
      },
      {
        id: 'MS-003-2',
        invoiceId: 'INV-003',
        amount: 2500,
        description: 'Content creation and social media execution',
        condition: '50+ posts published with engagement metrics',
        status: 'RELEASED',
        sequence: 2,
        completedAt: '2024-11-01T16:00:00Z',
      },
      {
        id: 'MS-003-3',
        invoiceId: 'INV-003',
        amount: 1000,
        description: 'Campaign report and analytics',
        condition: 'Final report with ROI analysis',
        status: 'RELEASED',
        sequence: 3,
        completedAt: '2024-11-20T10:00:00Z',
      },
    ],
    createdAt: '2024-09-15T10:00:00Z',
    updatedAt: '2024-11-20T10:00:00Z',
    daoName: 'Web3 Guild',
    projectType: 'Marketing',
    timeline: '10 weeks',
  },
  {
    id: 'INV-004',
    projectTitle: 'Smart Contract Security Audit',
    description: 'Comprehensive security audit of Clarity smart contracts for DEX protocol, including automated testing and manual review.',
    clientAddress: 'SP2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKNRV9EJ7',
    contractorAddress: 'SP4SECURITY1Z7JY4C9P7NDJMM5X1EQK3RKY4S8M',
    arbitratorAddress: 'SP1KFJXJ8Q9HV7YP3WGH98JN3JKZM7RQ2TKXHXF4N',
    totalAmount: 3500,
    currency: 'sBTC',
    status: 'ACTIVE',
    milestones: [
      {
        id: 'MS-004-1',
        invoiceId: 'INV-004',
        amount: 1050,
        description: 'Preliminary audit and automated testing',
        condition: 'Initial audit report with findings',
        status: 'RELEASED',
        sequence: 1,
        completedAt: '2024-11-18T15:00:00Z',
      },
      {
        id: 'MS-004-2',
        invoiceId: 'INV-004',
        amount: 2450,
        description: 'Comprehensive manual review and final report',
        condition: 'Final security audit report with recommendations',
        status: 'PENDING',
        sequence: 2,
      },
    ],
    createdAt: '2024-11-01T08:00:00Z',
    updatedAt: '2024-11-18T15:00:00Z',
    daoName: 'DeFi DAO',
    projectType: 'Security Audit',
    timeline: '3 weeks',
  },
  {
    id: 'INV-005',
    projectTitle: 'NFT Marketplace Backend Development',
    description: 'Build robust backend infrastructure for NFT marketplace including APIs, database design, and integration with IPFS.',
    clientAddress: 'SP3WEB3GUILD9MP66SW86PYKKNRV9EJ7MP66SW86P',
    contractorAddress: 'SP5BACKEND123Y4C9P7NDJMM5X1EQK3RKY4S8MPX',
    arbitratorAddress: 'SP1KFJXJ8Q9HV7YP3WGH98JN3JKZM7RQ2TKXHXF4N',
    totalAmount: 6000,
    currency: 'sBTC',
    status: 'DISPUTED',
    milestones: [
      {
        id: 'MS-005-1',
        invoiceId: 'INV-005',
        amount: 1800,
        description: 'Database schema and API design',
        condition: 'Approved architecture document',
        status: 'RELEASED',
        sequence: 1,
        completedAt: '2024-10-20T11:00:00Z',
      },
      {
        id: 'MS-005-2',
        invoiceId: 'INV-005',
        amount: 3000,
        description: 'Core API development and IPFS integration',
        condition: 'Working APIs with test coverage',
        status: 'DISPUTED',
        sequence: 2,
      },
      {
        id: 'MS-005-3',
        invoiceId: 'INV-005',
        amount: 1200,
        description: 'Performance optimization and deployment',
        condition: 'Production-ready deployment',
        status: 'PENDING',
        sequence: 3,
      },
    ],
    createdAt: '2024-10-05T13:00:00Z',
    updatedAt: '2024-11-22T09:00:00Z',
    daoName: 'NFT Collective',
    projectType: 'Backend Development',
    timeline: '7 weeks',
  },
];

// Mock AI parsing function
export const mockAIParseInvoice = async (description: string): Promise<AIParsedInvoice> => {
  // Simulate AI processing delay
  await new Promise(resolve => setTimeout(resolve, 1500));

  // Extract numbers for amount estimation
  const amountMatch = description.match(/(\d+(?:,\d+)?(?:\.\d+)?)\s*(sBTC|STX|BTC)/i);
  const totalAmount = amountMatch ? parseFloat(amountMatch[1].replace(',', '')) : 5000;

  // Parse milestones from description
  const milestoneKeywords = ['milestone', 'phase', 'payment', 'stage', 'deliverable'];
  const hasMilestones = milestoneKeywords.some(keyword => 
    description.toLowerCase().includes(keyword)
  );

  const milestones = hasMilestones ? [
    {
      amount: totalAmount * 0.3,
      percentage: 30,
      description: 'Initial development and setup',
      condition: 'Project kickoff and initial deliverables',
      sequence: 1,
    },
    {
      amount: totalAmount * 0.5,
      percentage: 50,
      description: 'Core implementation and testing',
      condition: 'Functional prototype with key features',
      sequence: 2,
    },
    {
      amount: totalAmount * 0.2,
      percentage: 20,
      description: 'Final delivery and documentation',
      condition: 'Complete project with documentation',
      sequence: 3,
    },
  ] : [
    {
      amount: totalAmount * 0.5,
      percentage: 50,
      description: 'Project development',
      condition: 'Milestone completion approval',
      sequence: 1,
    },
    {
      amount: totalAmount * 0.5,
      percentage: 50,
      description: 'Final delivery',
      condition: 'Project completion and approval',
      sequence: 2,
    },
  ];

  return {
    total_amount: totalAmount,
    currency: amountMatch?.[2] || 'sBTC',
    parties: {
      client: 'SP2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKNRV9EJ7',
      contractor: 'SP3FGQ8Z7JY4C9P7NDJMM5X1EQK3RKY4S8MP9QX2V',
    },
    milestones,
    arbitrator: 'SP1KFJXJ8Q9HV7YP3WGH98JN3JKZM7RQ2TKXHXF4N',
    project_scope: description.slice(0, 200),
    project_title: description.slice(0, 60).trim() + '...',
    timeline: '6-8 weeks',
    confidence: 0.94,
  };
};

// Mock DAO data - Enhanced with comprehensive details
export const mockDAOs: DAOProfile[] = [
  {
    id: 'dao_stacks_defi',
    name: 'Stacks DeFi Alliance',
    treasuryAddress: 'SP2XYZ456DEF789GHI012JKL345MNO678PQR901',
    totalBudget: 125500,
    availableBudget: 89300,
    activeInvoices: 23,
    completedInvoices: 45,
    members: 287,
    focus: ['DeFi', 'sBTC', 'Lending Protocols', 'Smart Contracts'],
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'dao_bitcoin_ai',
    name: 'Bitcoin AI Collective',
    treasuryAddress: 'SP3ABC123DEF456GHI789JKL012MNO345PQR678',
    totalBudget: 89300,
    availableBudget: 67200,
    activeInvoices: 18,
    completedInvoices: 32,
    members: 156,
    focus: ['AI Integration', 'Machine Learning', 'Oracles', 'Prediction Markets'],
    createdAt: '2024-02-20T00:00:00Z',
  },
  {
    id: 'dao_web3_gaming',
    name: 'Web3 Gaming Guild',
    treasuryAddress: 'SP4MNO901PQR234STU567VWX890YZA123BCD456',
    totalBudget: 67800,
    availableBudget: 45600,
    activeInvoices: 31,
    completedInvoices: 58,
    members: 423,
    focus: ['Gaming', 'NFTs', 'Community', 'Metaverse'],
    createdAt: '2024-03-10T00:00:00Z',
  },
  {
    id: 'dao_nft_innovators',
    name: 'NFT Innovators DAO',
    treasuryAddress: 'SP5EFG789HIJ012KLM345NOP678QRS901TUV234',
    totalBudget: 42600,
    availableBudget: 28400,
    activeInvoices: 15,
    completedInvoices: 29,
    members: 198,
    focus: ['NFTs', 'Digital Art', 'Collectibles', 'Generative Art'],
    createdAt: '2024-04-05T00:00:00Z',
  },
  {
    id: 'dao_rwa_tokenization',
    name: 'RWA Tokenization Collective',
    treasuryAddress: 'SP6WXY567ZAB890CDE123FGH456IJK789LMN012',
    totalBudget: 156200,
    availableBudget: 98500,
    activeInvoices: 27,
    completedInvoices: 41,
    members: 89,
    focus: ['Real World Assets', 'Tokenization', 'DeFi', 'Institutional Finance'],
    createdAt: '2024-05-12T00:00:00Z',
  },
];

// Mock contractor data - Enhanced with comprehensive profiles
export const mockContractors: ContractorProfile[] = [
  {
    id: 'contractor_alice_dev',
    walletAddress: 'SP2ALICE1234567890CONTRACTORDEV01',
    name: 'Alice Chen',
    rating: 4.9,
    completedProjects: 47,
    totalEarned: 376000,
    skills: ['Clarity', 'React', 'TypeScript', 'sBTC Integration', 'DeFi'],
    bio: 'Senior full-stack Stacks developer specializing in DeFi protocols and smart contract development. 5+ years of blockchain experience.',
    availability: 'available',
  },
  {
    id: 'contractor_bob_audit',
    walletAddress: 'SP3BOB4567890123AUDITSPECIALIST02',
    name: 'Bob Rodriguez',
    rating: 4.8,
    completedProjects: 32,
    totalEarned: 384000,
    skills: ['Security Audit', 'Clarity', 'Formal Verification', 'Penetration Testing', 'Smart Contract Security'],
    bio: 'Smart contract security expert with expertise in Clarity and formal verification. Former security researcher at major blockchain firms.',
    availability: 'busy',
  },
  {
    id: 'contractor_carol_design',
    walletAddress: 'SP4CAROL789012345DESIGNERFOCUS03',
    name: 'Carol Williams',
    rating: 4.7,
    completedProjects: 28,
    totalEarned: 168000,
    skills: ['UI/UX Design', 'Figma', 'Web3 Design', 'Brand Identity', 'User Research'],
    bio: 'Award-winning Web3 UI/UX designer focused on creating intuitive experiences for blockchain applications.',
    availability: 'available',
  },
  {
    id: 'contractor_dave_marketing',
    walletAddress: 'SP5DAVE012345678MARKETINGPRO04',
    name: 'Dave Kumar',
    rating: 4.6,
    completedProjects: 35,
    totalEarned: 175000,
    skills: ['Growth Marketing', 'Community Building', 'Content Strategy', 'Web3 Marketing', 'Social Media'],
    bio: 'Web3 growth marketing specialist with proven track record in DAO community building and token launches.',
    availability: 'available',
  },
  {
    id: 'contractor_eve_ai',
    walletAddress: 'SP6EVE345678901AIINTEGRATION05',
    name: 'Eve Johnson',
    rating: 4.9,
    completedProjects: 41,
    totalEarned: 615000,
    skills: ['AI Integration', 'Machine Learning', 'NLP', 'Smart Contract Automation', 'Python'],
    bio: 'AI/ML engineer specializing in blockchain integration. PhD in Computer Science, expertise in predictive analytics and automation.',
    availability: 'available',
  },
];

