[project]
name = "bitmind-smart-invoice"
description = "Smart Invoice Escrow System for DAOs on Stacks"
authors = ["BitMind Team"]
telemetry = true
cache_dir = ".cache"
requirements = []
boot_contracts = []

[contracts.smart-invoice-escrow]
path = "smart-invoice-escrow.clar"
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

