// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlvuswftjdpnqlyrzquz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsdnVzd2Z0amRwbnFseXJ6cXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzODExMTQsImV4cCI6MjA3NTk1NzExNH0.jOjLeqs9Y4glovC4936tJNP62UEs4ZdvAZElpdOXVwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});